### ISSUE TITLE
Revamp formatting to provide more context

### ISSUE THREAD

**Issue by fvcproductions** [fvcproductions/apprenticeships#7]
Right now, the list of apprenticeships is just a list but I'd really love to convert this to a full-fledged table that is easily filterable and digestible - similar to how the [`hiring-without-whiteboards`](https://github.com/poteto/hiring-without-whiteboards) works.

## Initial data points

- Name of apprenticeship & company associated
- Location

---

> ✅️ By submitting this issue, I have verified the following

* [x] Checked to see if the issue has already been discussed before 🤔️
* [x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by balexhill** [comment]
I'd be interested in making some edits! I'll get to it ASAP. Is there anything else I should keep in mind as far as formatting, or the Hiring Without Whiteboards example is mostly how you want it to look?

**Comment by fvcproductions** [comment]
Yes, that would be amazing! 

Since we don't have as many right now, we can just focus on filtering it by country and then adding the cities where the apprenticeship is available next to it along with a brief description.

So ideally something along the lines of:

```markdown
## Country

- [Company/Apprenticeship Name](link) | City/Cities | Description of company/apprenticeship
```

which would then look like this:

## United States

- [8th Light](https://8thlight.com/apprenticeship/) | Chicago, IL; Brooklyn, NY; London, UK; Los Angeles, CA | 8th Light is a software consultancy that is passionate about crafting beautiful and durable software products.

---

Do let me know if you have any other questions and thank you again for the support!

**Comment by fvcproductions** [comment]
@balexhill took care of this - thanks again!
