### ISSUE TITLE
Create a website 🌐️

### ISSUE THREAD

**Issue by fvcproductions** [fvcproductions/apprenticeships#8]
As the list grows, so will the pain of navigating through a Markdown list.

I would go with Airtable but the platform was not meant for open source collaboration.

Having a website or open source spreadsheet like configuration would be the better option.

[Docsify](https://github.com/docsifyjs/docsify) seems like the best option right now but I would like to look into other open source options.

---

> ✅️ By submitting this issue, I have verified the following

* [x] Checked to see if the issue has already been discussed before 🤔️
* [x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by fvcproductions** [comment]
Creating a static site with Hugo & Algolia now seems like the better option. Will start working on this soon enough! 😄

**Comment by Tirzahe** [comment]
Should the site allow viewers a way to submit apprenticeship programs they are aware of to be added to the list? Also, will the list be searchable by location and program focus?

**Comment by benjaminmodayil** [comment]
Hi @fvcproductions, are you looking for someone to create the site using the above stack and tools? I would love to help with this if you'd like.

**Comment by fvcproductions** [comment]
@benjaminmodayil That would be amazing - I'll go ahead and add you as a contributor and feel free to go ahead and create a PR with some initial scaffolding so we can get a discussion started. Everything would stay in the same repo.

But yeah, ideally we would Hugo for the base CMS and Algolia for easy searching. Each apprenticeship would just be a Markdown file with data fields like "location" and "description" being located in the front matter.

That's basically it. The theme would ideally be something super simple (like this: https://github.com/nanxiaobei/hugo-paper) but we can definitely iterate on that together.

Let me know if you have any questions!

**Comment by fvcproductions** [comment]
Some other things I'd like to happen in the future that I'll add in once a website is more finalized.

- make it easy for anyone (regardless of their technical background) to add on an apprenticeship either by opening a GitHub issue with all the details or by creating a PR themselves adding the new Markdown file
- create issue/PR templates for adding an apprenticeship and for updating apprenticeship info

**Comment by benjaminmodayil** [comment]
Awesome. I'll get started tomorrow on this and will reach out with that initial PR.

**Comment by fvcproductions** [comment]
@benjaminmodayil I've looked into domains and I think a good name for this repo and the website moving forward could be "Become an Apprentice".

The domain right now is definitely temporary but ideally, if we're going to go with that title, we can make it "become-an-apprentice.com" - open on Google Domains for $12/year.

What are your thoughts on this?

I want to make sure the domain and repo are similar if not the same but a lot of apprenticeship related domains are taken.

"apprenticeships.me" is open for $20/year and also has a nice ring to it.

**Comment by benjaminmodayil** [comment]
I like `apprenticeships.me` and how that sounds. I'm not too sure about `become-an-apprentice`. I think having hyphens might not be ideal for someone going to the site, but I'm not too sure. I think this is something that can wait though. I just wanted to know if the site was going to have a title on the page so I can assign a spot for it.

Plus, whatever is chosen as the title probably should be reflected in the domain as well. I'll take a look at other possible options, but I think "apprenticeships.me" is the top choice at the moment.

**Comment by fvcproductions** [comment]
Done - but needs more fine tuning - will add issues to address these.
